version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: databasedb
      MYSQL_USER: student1
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306